{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "passbolt-operator.fullname" . }}-metrics
  labels:
    {{- include "passbolt-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8443
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "passbolt-operator.selectorLabels" . | nindent 8 }}
{{- end }}