apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    {{- include "passbolt-operator.labels" . | nindent 4 }}
  name: {{ include "passbolt-operator.service.metrics.name" . }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "passbolt-operator.selectorLabels" . | nindent 4 }}
