apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    {{- include "passbolt-operator.labels" . | nindent 4 }}
  name: {{ include "passbolt-operator.certificate.name" . }}
spec:
  dnsNames:
  - {{ include "passbolt-operator.service.webhook.name" . }}.{{ .Release.Namespace }}.svc
  - {{ include "passbolt-operator.service.webhook.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "passbolt-operator.certificate.issuer.name" . }}
  secretName: {{ include "passbolt-operator.certificate.secret.name" . }}
