apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    {{- include "passbolt-operator.labels" . | nindent 4 }}
  name: {{ include "passbolt-operator.certificate.issuer.name" . }}
spec:
  selfSigned: {}
