apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    {{- include "passbolt-operator.labels" . | nindent 4 }}
  name: {{ include "passbolt-operator.service.webhook.name" . }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{ include "passbolt-operator.selectorLabels" . | nindent 4 }}
