apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "passbolt-operator.namespaced-certificate.name" . }}
  labels:
    app.kubernetes.io/component: webhook
    {{- include "passbolt-operator.labels" . | nindent 4 }}
  name: {{ include "passbolt-operator.webhook.validation.name" . }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "passbolt-operator.service.webhook.name" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-passbolt-tagesspiegel-de-v1alpha3-passboltsecret
  failurePolicy: Fail
  name: vpassboltsecret.tagesspiegel.de
  rules:
  - apiGroups:
    - passbolt.tagesspiegel.de
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - passboltsecrets
  sideEffects: None
