blank_issues_enabled: false
contact_links:
  - name: Questions and Community Support
    url: https://github.com/urbanmedia/passbolt-operator-helm/discussions
    about: Please ask and answer questions here.