# Default values for passbolt-secret.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# leaveOnDelete is a flag to indicate if the Kubernetes secret should be deleted when the
# corresponding passbolt secret is deleted. If set to true, the secret will be deleted when
# the passbolt secret is deleted. If set to false, the secret will not be deleted when the
# passbolt secret is deleted.
leaveOnDelete: false

secrets: []
  # - # kubernetesSecretKey is the name of the secret key to be created in Kubernetes secrets resource
  #   kubernetesSecretKey: ""
  #   # passboltSecret represents the passbolt secret to be referenced in the passbolt instance
  #   passboltSecret:
  #     # name is the name of the passbolt secret to be referenced
  #     name: ""
  #     # field is the name of the passbolt secret field to be referenced
  #     # valid values are: "username", "password", "uri"
  #     field: ""