# Default values for passbolt-secret.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# -- leaveOnDelete is a flag to indicate if the Kubernetes secret should be deleted when the
# corresponding passbolt secret is deleted. If set to true, the secret will be deleted when
# the passbolt secret is deleted. If set to false, the secret will not be deleted when the
# passbolt secret is deleted.
leaveOnDelete: false

# -- The type of the Kubernetes secret to be created
# Valid values are: "Opaque", "kubernetes.io/dockerconfigjson"
secretType: Opaque

# -- The name of the Passbolt secret to be referenced
# This option is only used when the secretType is set to "kubernetes.io/dockerconfigjson"
passboltSecretName: ""

# -- A list of secrets to be referenced in the passbolt instance
secrets: []
      # secrets[*].kubernetesSecretKey -- kubernetesSecretKey is the name of the secret key to be created in Kubernetes secrets resource
  # - kubernetesSecretKey: ""
      # secrets[*].passboltSecret -- passboltSecret represents the passbolt secret to be referenced in the passbolt instance
  #   passboltSecret:
        # secrets[*].passboltSecret.name -- name is the name of the passbolt secret to be referenced
  #     name: ""
        # secrets[*].passboltSecret.field -- field is the name of the passbolt secret field to be referenced
        # valid values are: "username", "password", "uri"
  #     field: ""
        # secrets[*].passboltSecret.value -- value is the plain text value of the secret.
        # This field allows to set a static value or using go templating to generate the value.
        # Valid template variables are:
        #   - Password
        #   - Username
        #   - URI
        # Example: "postgresql://{{ .Username }}:{{ .Password }}@{{ .URI }}"
  #     value: ""
