# Default values for passbolt-secret.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# -- leaveOnDelete is a flag to indicate if the Kubernetes secret should be deleted when the
# corresponding passbolt secret is deleted. If set to true, the secret will be deleted when
# the passbolt secret is deleted. If set to false, the secret will not be deleted when the
# passbolt secret is deleted.
leaveOnDelete: false

# -- The type of the Kubernetes secret to be created
# Valid values are: "Opaque", "kubernetes.io/dockerconfigjson"
secretType: Opaque

# -- The ID of the Passbolt secret to be referenced
# This option is only used when the secretType is set to "kubernetes.io/dockerconfigjson"
passboltSecretID: ""

# -- A list of secrets to be referenced in the passbolt instance
passboltSecrets: {}
  # <k8s-secret-key>:
    # id: <passbolt-secret-id>
    # field: <passbolt-secret-field>
    # value: <passbolt-secret-value>
  #
  # Example:
  # my-key:
  #   id: 00000000-0000-0000-0000-000000000000
  #   field: username
  #   # value: mysql://{{.Username}}:{{.Password}}@{{.URI}}:3306/my-db

plainTextSecrets: {}
  # <secret-key>: <secret-value>
