apiVersion: passbolt.tagesspiegel.de/v1alpha1
kind: PassboltSecret
metadata:
  name: {{ include "passbolt-secret.fullname" . }}
  labels:
    {{- include "passbolt-secret.labels" . | nindent 4 }}
spec:
  leaveOnDelete: false
  secrets:
    {{- toYaml .Values.secrets | nindent 4 }}