apiVersion: passbolt.tagesspiegel.de/v1alpha2
kind: PassboltSecret
metadata:
  name: {{ include "passbolt-secret.fullname" . }}
  labels:
    {{- include "passbolt-secret.labels" . | nindent 4 }}
spec:
  leaveOnDelete: {{ .Values.leaveOnDelete }}
  secretType: {{ .Values.secretType }}
  {{- if eq .Values.secretType "kubernetes.io/dockerconfigjson" }}
  passboltSecretName: {{ .Values.passboltSecretName }}
  {{- else }}
  secrets:
    {{- toYaml .Values.secrets | nindent 4 }}
  {{- end }}
