apiVersion: passbolt.tagesspiegel.de/v1alpha3
kind: PassboltSecret
metadata:
  name: {{ include "passbolt-secret.fullname" . }}
  labels:
    {{- include "passbolt-secret.labels" . | nindent 4 }}
spec:
  leaveOnDelete: {{ .Values.leaveOnDelete }}
  secretType: {{ .Values.secretType }}
  {{- if eq .Values.secretType "kubernetes.io/dockerconfigjson" }}
  passboltSecreID: {{ .Values.passboltSecretID }}
  {{- else }}
  passboltSecrets:
    {{- toYaml .Values.passboltSecrets | nindent 4 }}
  plainTextFields:
    {{- toYaml .Values.plainTextSecrets | nindent 4 }}
  {{- end }}
